### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by reddevil1310** [xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master#3]
Hi, i am a beginner.I have successfully run this project with mvtec datasets. I try it with my dataset but got error:

Traceback (most recent call last):
  File "main.py", line 305, in <module>
    main()
  File "main.py", line 137, in main
    for (x, y, mask) in tqdm(test_dataloader, '| feature extraction | test | %s |' % class_name):
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\tqdm\std.py", line 1167, in __iter__
    for obj in iterable:
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\torch\utils\data\_utils\collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\torch\utils\data\_utils\collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "H:\ProjectPycharm\PaDiM-Anomaly-Detection-Localization\venv\lib\site-packages\torch\utils\data\_utils\collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 224, 224] at entry 0 and [1, 224, 224] at entry 31

How can i fix it ? thank you.

**Comment by xiahaifeng1995** [comment]
Hi,
There might be grayscale images in your dataset, some images have 3 channels, while others have 1 channel. Try to add a transform to convert colored images to grayscale or vice versa.

**Comment by reddevil1310** [comment]
thanks for your help. Is the mask grayscale images?

**Comment by reddevil1310** [comment]
when I use 12 error images, i get the error: 
RuntimeError: stack expects each tensor to be equal size, but got [3, 224, 224] at entry 0 and [1, 224, 224] at entry 11
It seems last entry is always [1,224,224].
I have successfully tested on mvtec datasets, but I cannot fix the error to run on my datasets. :((

**Comment by reddevil1310** [comment]
i fixed it. thank you very much
